sources:
  - name: raw
    dataset: delays
    tables:
      - name: raw_trips
        meta:
          dagster:
            asset_key: ["raw_trips"]
      - name: raw_stops
        meta:
          dagster:
            asset_key: ["raw_stops"]
      - name: raw_stop_time_updates
        meta:
          dagster:
            asset_key: ["raw_stop_time_updates"]
      - name: raw_stop_times
        meta:
          dagster:
            asset_key: ["raw_stop_times"]