-- select
-- from raw_realtime__stop_time_updates
-- left join raw_stops on
--     raw_realtime__stop_time_updates.stop_id = raw_stops.stop_id and
--     raw_realtime__stop_time_updates.
-- where
--     raw_stops.location_type 
